aston_homepage:
    path:     /
    defaults: { _controller: AstonBundle:Default:index }
aston_dasboard:
    path:     /dashboard/{stats}
    defaults: { _controller: AstonBundle:Default:dashboard,stats:0 }
#    requirements:
#       stats: "[a-z][a-z]"
aston_about:
    path:     /about
    defaults: { _controller: AstonBundle:Default:about }
    
   # SessionsController
   
aston_sess_write:
    path:     /write
    defaults: { _controller: AstonBundle:Session:writeSess }

aston_sess_read:
    path:     /read
    defaults: { _controller: AstonBundle:Session:readSess }

aston_sess_tpl:
    path:     /tpl
    defaults: { _controller: AstonBundle:Session:tpl }